# Use the official node image as the base image
FROM node:18-alpine

# Set the working directory to /app
WORKDIR /app

# Copy the package.json and package-lock.json to the working directory
COPY package*.json ./

# Install the dependencies
RUN npm install

# Copy the source files, including envs and src, to the working directory
COPY . .

# Specify the command to run when the container starts
CMD ["npm", "start"]
